---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mesh-api-secret
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgDCRDSACZzZrd5Q+e4YD3uQdS+woX2JgRCKkIKixrVhRlJ55hoU8cV3qhW5L00tL+FzWi/fspD9KLITzxi1VJZaRGG6Bv4FiyLms35tdsugQzHEBC1NsrWfF0wXleP5MVhDZrRNbB7UGLxi/iIofUgu6Tu+M9FJY7S+TR63ucE69VJ3zFAcyYp/4pO1f9vPm/W2EqXbuPtwgqXxPq6KRsezDbrs82fsMNJTm5UGd+1i5XsdMIUWNa4bMXAkxLvi8ohnjDmbz8plsM2ydaHCJP45BsB4sHHDYOqazsg6OntdYBxSUWdM8d5gkCsgWutyIA1Lqh74uBd/i32H/5IXmzuWxbpKIiy8sB/sv5izu+W/UfqzbDZIWglDfAZQ5jLAVp0ZFRUBx6eVwsgOviPWMqqfqw3C6xsBs78p0W9H7c9IF4ZRn1LsE/hgon7Pf8Bk7M1+ecMcPqJ+Vp46lv7q1MzBZmMU312PLjFQkadVfC6/u4a/QV/1X1lYEdkS42RC428tvuK0Dwf7uAAB2nYgA+BVrovDimld7noUBLmXyu8YUH7fEYQt85PIhHkrLVjG64nrXFwH0waZmULpW4j+znYlxma889OzwiuvGw1G8uyaWZUwOk2LdXVbEHQUVxKX70dFdHrUWhU5jBotYlYhDjBwD4T5cGTODhUBUGRRa87f6OpBFAcZiBE45XxHsnsHbzPeDUNpUy2kMFUuiQ==
    DB_USER: AgB0IZ6H4+4FoDc+XQUogMMryBnYQ2T9XSPkCNg5BoifDRHl2FIipxXsp5wW4E6UerqqoL9S0vt48epR/Oz+d8J5czRLAsdHryEuXkohvnjY9xfPave6VOwrRhUi7Ref5pO/hXXrXZZWv/KJL3UogbOYwmabVCUpo5jyoQtkmtujoeorG8cKwBsVQRPZtw0/jMAatjFwvU8IHGBhsdH4DOnMiVyc96kYIE+EU9qz0uDJSgppjM50TfMq4J5fu9+1m3dnrd7/K1uZfhW0i/ca1Dv22JSL6cIebjR0fU/BO3+9CWBPeEmVVIXCYl7Yl7IOxIh4J+jA/hj2oXpv5lEv1tGJWwiqtUPSg1on1uD7Jl+y1MBwxk7giShw/lv9U4HV3jIPxhdMQ/A24igJZwICMlpGIdBRB9KhCIEy6dVkwNlR2eo9vBMmjZo5+m+ILAb4EHHakWDJJcJ9s+SmwpAYY2H5fch9mTFaADK1QgN4U73yR6PMQUXDcWTf0r6jVnJPtVVusaPBvmA1EN7YpUpx/iRzFjdH++13GrBPDDQfKF06m7C2aHXfgXbOhDvsGdePEhDHO1YTzoEQu7BOkgsz7UtCw3hMGKy2Z6/vUZfKmWVbBVJm+Fr3Kn7YiF818NpPk0L2yuZAGotG3KEJNuMBJWG7vd+5gEg0yV8WDpXCMxFt1kiCns2nLdK3U/OGmhDd2Hs3vxYK
  template:
    metadata:
      name: mesh-api-secret
      namespace: dev
